# coding_challenge_data.gd — Data-driven challenge definitions for the DjangoQuest IDE
# Add new challenges by appending dictionaries to the arrays below.
# No code changes needed in the UI script — it reads these dictionaries directly.
extends Node

# ─── PYTHON CHALLENGES ───────────────────────────────────────────────────────

static var python_challenges: Array = [
	# ── Debug ──
	{
		"id": "py_debug_01",
		"topic": "python",
		"type": "debug",
		"title": "Fix the Print Statement",
		"timed": false,
		"time_limit": 0,
		"file_name": "hello.py",
		"mission_steps": [
			"Read the code on the right",
			"Find the typo on the highlighted line",
			"Select the correct fix below the code",
		],
		"hint": "Python's built-in function to display text is spelled p-r-i-n-t.",
		"code_lines": [
			"# My first Python program",
			"def greet():",
			"    prnt('Hello, World!')",
			"    return",
			"",
			"greet()",
		],
		"bug_line": 2,
		"options": [
			{"text": "print('Hello, World!')", "correct": true},
			{"text": "Print('Hello, World!')", "correct": false},
			{"text": "printf('Hello, World!')", "correct": false},
		],
		"correct_output": "Hello, World!",
		"error_output": "NameError: name 'prnt' is not defined",
		"output_type": "terminal",
	},
	{
		"id": "py_debug_02",
		"topic": "python",
		"type": "debug",
		"title": "Fix the Variable",
		"timed": false,
		"time_limit": 0,
		"file_name": "variables.py",
		"mission_steps": [
			"This code should print a greeting with the user's name",
			"Find why it's crashing",
			"Select the correct fix",
		],
		"hint": "Variable names are case-sensitive in Python.",
		"code_lines": [
			"name = 'Mateo'",
			"age = 18",
			"print('Hello, ' + Name)",
		],
		"bug_line": 2,
		"options": [
			{"text": "print('Hello, ' + name)", "correct": true},
			{"text": "print('Hello, ' + NAME)", "correct": false},
			{"text": "print('Hello, ' + 'Name')", "correct": false},
		],
		"correct_output": "Hello, Mateo",
		"error_output": "NameError: name 'Name' is not defined",
		"output_type": "terminal",
	},
	{
		"id": "py_debug_03",
		"topic": "python",
		"type": "debug",
		"title": "Fix the Loop",
		"timed": true,
		"time_limit": 45,
		"file_name": "loop.py",
		"mission_steps": [
			"This code should print numbers 1 to 5",
			"Find the syntax error",
			"Select the fix before time runs out!",
		],
		"hint": "for loops in Python need a colon at the end.",
		"code_lines": [
			"for i in range(1, 6)",
			"    print(i)",
		],
		"bug_line": 0,
		"options": [
			{"text": "for i in range(1, 6):", "correct": true},
			{"text": "for i in range(1, 6);", "correct": false},
			{"text": "for (i in range(1, 6)):", "correct": false},
		],
		"correct_output": "1\n2\n3\n4\n5",
		"error_output": "SyntaxError: expected ':'",
		"output_type": "terminal",
	},
	# ── Predict Output ──
	{
		"id": "py_predict_01",
		"topic": "python",
		"type": "predict_output",
		"title": "What Gets Printed?",
		"timed": false,
		"time_limit": 0,
		"file_name": "mystery.py",
		"mission_steps": [
			"Read the code carefully",
			"Think about what each line does",
			"Select what the output will be",
		],
		"hint": "The + operator joins strings together.",
		"code_lines": [
			"a = 'Django'",
			"b = 'Quest'",
			"print(a + b)",
		],
		"bug_line": -1,
		"options": [
			{"text": "DjangoQuest", "correct": true},
			{"text": "Django Quest", "correct": false},
			{"text": "Django+Quest", "correct": false},
		],
		"correct_output": "DjangoQuest",
		"error_output": "",
		"output_type": "terminal",
	},
	# ── Follow Steps ──
	{
		"id": "py_steps_01",
		"topic": "python",
		"type": "follow_steps",
		"title": "Create a Function",
		"timed": false,
		"time_limit": 0,
		"file_name": "functions.py",
		"mission_steps": [
			"We need a function that adds two numbers",
			"The function is missing its body",
			"Select the correct code to complete it",
		],
		"hint": "Use the return keyword to send back a value.",
		"code_lines": [
			"def add(a, b):",
			"    # What goes here?",
			"",
			"result = add(3, 5)",
			"print(result)",
		],
		"bug_line": 1,
		"options": [
			{"text": "return a + b", "correct": true},
			{"text": "print(a + b)", "correct": false},
			{"text": "a + b", "correct": false},
		],
		"correct_output": "8",
		"error_output": "None",
		"output_type": "terminal",
	},
	# ── Free Type ──
	{
		"id": "py_free_01",
		"topic": "python",
		"type": "free_type",
		"title": "Write a Print Statement",
		"timed": false,
		"time_limit": 0,
		"file_name": "hello.py",
		"show_output": true,
		"mission_steps": [
			"Write a line of Python code",
			"It should print 'Hello, World!' to the console",
			"Use the print() function",
		],
		"hint": "The syntax is: print('your text here')",
		"code_lines": [
			"# Write your code below",
			"",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "Type your Python code here...",
		"expected_answers": [
			"print('Hello, World!')",
			'print("Hello, World!")',
		],
		"correct_output": "Hello, World!",
		"error_output": "SyntaxError or unexpected output",
		"output_type": "terminal",
	},
	{
		"id": "py_free_02",
		"topic": "python",
		"type": "free_type",
		"title": "Create a Variable",
		"timed": false,
		"time_limit": 0,
		"file_name": "variables.py",
		"show_output": false,
		"mission_steps": [
			"Create a variable called 'name'",
			"Assign it the value 'DjangoQuest'",
			"Use a single equals sign (=) for assignment",
		],
		"hint": "The syntax is: variable_name = 'value'",
		"code_lines": [
			"# Create a variable below",
			"",
			"print(name)  # This should print: DjangoQuest",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "name = ...",
		"expected_answers": [
			"name = 'DjangoQuest'",
			'name = "DjangoQuest"',
		],
		"correct_output": "DjangoQuest",
		"error_output": "NameError: name 'name' is not defined",
		"output_type": "terminal",
	},
]

# ─── HTML CHALLENGES ─────────────────────────────────────────────────────────

static var html_challenges: Array = [
	{
		"id": "html_debug_01",
		"topic": "html",
		"type": "debug",
		"title": "Fix the Heading",
		"timed": false,
		"time_limit": 0,
		"file_name": "index.html",
		"mission_steps": [
			"This page should show a heading",
			"Find the broken HTML tag",
			"Select the correct fix",
		],
		"hint": "HTML heading tags use the letter 'h' followed by a number.",
		"code_lines": [
			"<!DOCTYPE html>",
			"<html>",
			"<body>",
			"  <h1>Welcome to DjangoQuest<h1>",
			"</body>",
			"</html>",
		],
		"bug_line": 3,
		"options": [
			{"text": "<h1>Welcome to DjangoQuest</h1>", "correct": true},
			{"text": "<h1>Welcome to DjangoQuest<h1/>", "correct": false},
			{"text": "<h1>Welcome to DjangoQuest</H1>", "correct": false},
		],
		"correct_output": "[b]Welcome to DjangoQuest[/b]",
		"error_output": "⚠ Page not rendering correctly",
		"output_type": "browser",
	},
	{
		"id": "html_steps_01",
		"topic": "html",
		"type": "follow_steps",
		"title": "Add a Paragraph",
		"timed": false,
		"time_limit": 0,
		"file_name": "index.html",
		"mission_steps": [
			"The page has a heading but no paragraph",
			"Add a paragraph below the heading",
			"Select the right HTML to fill the blank",
		],
		"hint": "Paragraphs use the <p> tag.",
		"code_lines": [
			"<!DOCTYPE html>",
			"<html>",
			"<body>",
			"  <h1>My Website</h1>",
			"  <!-- Add paragraph here -->",
			"</body>",
			"</html>",
		],
		"bug_line": 4,
		"options": [
			{"text": "<p>Hello, welcome to my site!</p>", "correct": true},
			{"text": "<paragraph>Hello!</paragraph>", "correct": false},
			{"text": "<text>Hello!</text>", "correct": false},
		],
		"correct_output": "[b]My Website[/b]\n\nHello, welcome to my site!",
		"error_output": "[b]My Website[/b]",
		"output_type": "browser",
	},
	{
		"id": "html_predict_01",
		"topic": "html",
		"type": "predict_output",
		"title": "What Will the Page Show?",
		"timed": true,
		"time_limit": 30,
		"file_name": "quiz.html",
		"mission_steps": [
			"Read the HTML code",
			"Think about what will appear in the browser",
			"Select the correct output",
		],
		"hint": "<ul> creates a bulleted list, <li> is each bullet point.",
		"code_lines": [
			"<h2>Shopping List</h2>",
			"<ul>",
			"  <li>Eggs</li>",
			"  <li>Bread</li>",
			"</ul>",
		],
		"bug_line": -1,
		"options": [
			{"text": "Shopping List\n• Eggs\n• Bread", "correct": true},
			{"text": "Shopping List\n1. Eggs\n2. Bread", "correct": false},
			{"text": "Shopping List Eggs Bread", "correct": false},
		],
		"correct_output": "[b]Shopping List[/b]\n• Eggs\n• Bread",
		"error_output": "",
		"output_type": "browser",
	},
	{
		"id": "html_debug_02",
		"topic": "html",
		"type": "debug",
		"title": "Fix the Link",
		"timed": false,
		"time_limit": 0,
		"file_name": "index.html",
		"mission_steps": [
			"This link should go to google.com",
			"The tag attribute is wrong",
			"Select the correct fix",
		],
		"hint": "Links use the 'href' attribute, not 'link' or 'src'.",
		"code_lines": [
			"<a link='https://google.com'>Google</a>",
		],
		"bug_line": 0,
		"options": [
			{"text": "<a href='https://google.com'>Google</a>", "correct": true},
			{"text": "<a src='https://google.com'>Google</a>", "correct": false},
			{"text": "<a url='https://google.com'>Google</a>", "correct": false},
		],
		"correct_output": "[color=CORNFLOWER_BLUE][u]Google[/u][/color]",
		"error_output": "⚠ Link is not clickable",
		"output_type": "browser",
	},
	{
		"id": "html_debug_03",
		"topic": "html",
		"type": "debug",
		"title": "Fix the Image",
		"timed": true,
		"time_limit": 40,
		"file_name": "gallery.html",
		"mission_steps": [
			"The image isn't showing on the page",
			"Find the error in the img tag",
			"Fix it before time runs out!",
		],
		"hint": "Images use 'src' for the source URL, not 'href'.",
		"code_lines": [
			"<h2>My Photo</h2>",
			"<img href='photo.jpg' alt='My photo'>",
		],
		"bug_line": 1,
		"options": [
			{"text": "<img src='photo.jpg' alt='My photo'>", "correct": true},
			{"text": "<img link='photo.jpg' alt='My photo'>", "correct": false},
			{"text": "<image src='photo.jpg' alt='My photo'>", "correct": false},
		],
		"correct_output": "[b]My Photo[/b]\n\n[Image: photo.jpg]",
		"error_output": "[b]My Photo[/b]\n\n⚠ Broken image icon",
		"output_type": "browser",
	},
	{
		"id": "html_steps_02",
		"topic": "html",
		"type": "follow_steps",
		"title": "Create a Link",
		"timed": false,
		"time_limit": 0,
		"file_name": "nav.html",
		"mission_steps": [
			"We need a link to the About page",
			"The link text should say 'About Us'",
			"Select the correct HTML",
		],
		"hint": "Links use <a href='url'>text</a> format.",
		"code_lines": [
			"<nav>",
			"  <a href='/'>Home</a>",
			"  <!-- Add About link here -->",
			"</nav>",
		],
		"bug_line": 2,
		"options": [
			{"text": "<a href='/about'>About Us</a>", "correct": true},
			{"text": "<link to='/about'>About Us</link>", "correct": false},
			{"text": "<url='/about'>About Us</url>", "correct": false},
		],
		"correct_output": "Home | [color=CORNFLOWER_BLUE][u]About Us[/u][/color]",
		"error_output": "Home | (missing link)",
		"output_type": "browser",
	},
	{
		"id": "html_steps_03",
		"topic": "html",
		"type": "follow_steps",
		"title": "Build a Form",
		"timed": false,
		"time_limit": 0,
		"file_name": "contact.html",
		"mission_steps": [
			"We need a text input for the user's name",
			"Add an input element of type 'text'",
			"Select the correct HTML",
		],
		"hint": "Input elements use <input type='text'> format.",
		"code_lines": [
			"<form>",
			"  <label>Name:</label>",
			"  <!-- Add input here -->",
			"  <button>Submit</button>",
			"</form>",
		],
		"bug_line": 2,
		"options": [
			{"text": "<input type='text' name='username'>", "correct": true},
			{"text": "<textbox name='username'>", "correct": false},
			{"text": "<field type='text' name='username'>", "correct": false},
		],
		"correct_output": "Name: [___________] [Submit]",
		"error_output": "Name: (missing input) [Submit]",
		"output_type": "browser",
	},
	{
		"id": "html_predict_02",
		"topic": "html",
		"type": "predict_output",
		"title": "Nested Tags",
		"timed": false,
		"time_limit": 0,
		"file_name": "page.html",
		"mission_steps": [
			"Read the HTML carefully",
			"Notice the bold and italic tags",
			"What will the browser display?",
		],
		"hint": "<strong> makes text bold, <em> makes it italic.",
		"code_lines": [
			"<p>This is <strong>important</strong> and <em>urgent</em>.</p>",
		],
		"bug_line": -1,
		"options": [
			{"text": "This is important (bold) and urgent (italic).", "correct": true},
			{"text": "This is <strong>important</strong> and <em>urgent</em>.", "correct": false},
			{"text": "This is IMPORTANT and URGENT.", "correct": false},
		],
		"correct_output": "This is [b]important[/b] and [i]urgent[/i].",
		"error_output": "",
		"output_type": "browser",
	},
	{
		"id": "html_free_02",
		"topic": "html",
		"type": "free_type",
		"title": "Write a Paragraph",
		"timed": false,
		"time_limit": 0,
		"file_name": "about.html",
		"show_output": true,
		"mission_steps": [
			"Write a paragraph that says 'Welcome!'",
			"Use the <p> tag",
			"Include the opening AND closing tag",
		],
		"hint": "Paragraphs look like: <p>text</p>",
		"code_lines": [
			"<body>",
			"  <h1>About</h1>",
			"  <!-- Write your paragraph -->",
			"</body>",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "<p>...</p>",
		"expected_answers": [
			"<p>Welcome!</p>",
		],
		"correct_output": "[b]About[/b]\n\nWelcome!",
		"error_output": "⚠ Invalid HTML",
		"output_type": "browser",
	},
	# ── Free Type ──
	{
		"id": "html_free_01",
		"topic": "html",
		"type": "free_type",
		"title": "Write a Heading",
		"timed": false,
		"time_limit": 0,
		"file_name": "index.html",
		"show_output": true,
		"mission_steps": [
			"Write an HTML heading that says 'Hello'",
			"Use the h1 tag",
			"Don't forget the closing tag!",
		],
		"hint": "HTML headings look like: <h1>text</h1>",
		"code_lines": [
			"<body>",
			"  <!-- Write your heading below -->",
			"",
			"</body>",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "<h1>...</h1>",
		"expected_answers": [
			"<h1>Hello</h1>",
		],
		"correct_output": "[b]Hello[/b]",
		"error_output": "⚠ Invalid HTML",
		"output_type": "browser",
	},
]

# ─── CSS CHALLENGES ──────────────────────────────────────────────────────────

static var css_challenges: Array = [
	{
		"id": "css_debug_01",
		"topic": "css",
		"type": "debug",
		"title": "Fix the Color",
		"timed": false,
		"time_limit": 0,
		"file_name": "style.css",
		"mission_steps": [
			"The heading should be blue but it's not working",
			"Find the CSS property error",
			"Select the correct fix",
		],
		"hint": "The CSS property for text color is just 'color', not 'text-color'.",
		"code_lines": [
			"h1 {",
			"    text-color: blue;",
			"    font-size: 24px;",
			"}",
		],
		"bug_line": 1,
		"options": [
			{"text": "color: blue;", "correct": true},
			{"text": "font-color: blue;", "correct": false},
			{"text": "txt-color: blue;", "correct": false},
		],
		"correct_output": "[color=CORNFLOWER_BLUE][b]Hello World[/b][/color]\n\nThe heading is now blue!",
		"error_output": "[b]Hello World[/b]\n\n⚠ Heading color unchanged",
		"output_type": "browser",
	},
	{
		"id": "css_steps_01",
		"topic": "css",
		"type": "follow_steps",
		"title": "Center the Text",
		"timed": false,
		"time_limit": 0,
		"file_name": "style.css",
		"mission_steps": [
			"We need to center the heading text",
			"The CSS rule is incomplete",
			"Select the correct property to add",
		],
		"hint": "The CSS property to align text is 'text-align'.",
		"code_lines": [
			"h1 {",
			"    font-size: 32px;",
			"    /* Add centering here */",
			"}",
		],
		"bug_line": 2,
		"options": [
			{"text": "text-align: center;", "correct": true},
			{"text": "align: center;", "correct": false},
			{"text": "position: center;", "correct": false},
		],
		"correct_output": "[center][b]Welcome![/b][/center]\n\nText is now centered!",
		"error_output": "[b]Welcome![/b]\n\n(text is left-aligned)",
		"output_type": "browser",
	},
	{
		"id": "css_predict_01",
		"topic": "css",
		"type": "predict_output",
		"title": "What Color Is It?",
		"timed": true,
		"time_limit": 20,
		"file_name": "style.css",
		"mission_steps": [
			"Read the CSS rule",
			"Determine what color the paragraph text will be",
			"Select the answer quickly!",
		],
		"hint": "The last rule wins when there are conflicts.",
		"code_lines": [
			"p {",
			"    color: red;",
			"    color: green;",
			"}",
		],
		"bug_line": -1,
		"options": [
			{"text": "Green (last rule wins)", "correct": true},
			{"text": "Red (first rule wins)", "correct": false},
			{"text": "Both colors mixed", "correct": false},
		],
		"correct_output": "[color=GREEN]This paragraph is green.[/color]",
		"error_output": "",
		"output_type": "browser",
	},
	{
		"id": "css_debug_02",
		"topic": "css",
		"type": "debug",
		"title": "Fix the Background",
		"timed": false,
		"time_limit": 0,
		"file_name": "style.css",
		"mission_steps": [
			"The body should have a dark background",
			"The property name is incorrect",
			"Select the correct fix",
		],
		"hint": "The CSS property for background color is 'background-color', not 'bg-color'.",
		"code_lines": [
			"body {",
			"    bg-color: #1e1e2e;",
			"    color: white;",
			"}",
		],
		"bug_line": 1,
		"options": [
			{"text": "background-color: #1e1e2e;", "correct": true},
			{"text": "back-color: #1e1e2e;", "correct": false},
			{"text": "bgcolor: #1e1e2e;", "correct": false},
		],
		"correct_output": "Dark background with white text!",
		"error_output": "⚠ Background is still white",
		"output_type": "browser",
	},
	{
		"id": "css_debug_03",
		"topic": "css",
		"type": "debug",
		"title": "Fix the Font Size",
		"timed": true,
		"time_limit": 30,
		"file_name": "style.css",
		"mission_steps": [
			"The heading font size isn't applying",
			"Check if the value has proper units",
			"Fix it quickly!",
		],
		"hint": "CSS sizes need units like 'px', 'em', or 'rem'. Just a number won't work.",
		"code_lines": [
			"h1 {",
			"    font-size: 32;",
			"}",
		],
		"bug_line": 1,
		"options": [
			{"text": "font-size: 32px;", "correct": true},
			{"text": "font-size: 32p;", "correct": false},
			{"text": "font-size: big;", "correct": false},
		],
		"correct_output": "[b]Big Heading![/b]\n\nFont is now 32px",
		"error_output": "[b]Heading[/b]\n\n⚠ Font size unchanged",
		"output_type": "browser",
	},
	{
		"id": "css_steps_02",
		"topic": "css",
		"type": "follow_steps",
		"title": "Add a Border",
		"timed": false,
		"time_limit": 0,
		"file_name": "style.css",
		"mission_steps": [
			"Add a border around the div",
			"It should be 2px, solid, and black",
			"Select the correct CSS",
		],
		"hint": "Border shorthand: border: width style color;",
		"code_lines": [
			".card {",
			"    padding: 16px;",
			"    /* Add border here */",
			"}",
		],
		"bug_line": 2,
		"options": [
			{"text": "border: 2px solid black;", "correct": true},
			{"text": "border: solid 2px;", "correct": false},
			{"text": "outline: 2px black;", "correct": false},
		],
		"correct_output": "┌──────────────┐\n│  Card content │\n└──────────────┘",
		"error_output": "Card content (no border)",
		"output_type": "browser",
	},
	{
		"id": "css_steps_03",
		"topic": "css",
		"type": "follow_steps",
		"title": "Add Padding",
		"timed": false,
		"time_limit": 0,
		"file_name": "style.css",
		"mission_steps": [
			"The button text is too close to the edges",
			"Add padding to give it breathing room",
			"Select the correct CSS",
		],
		"hint": "Padding adds space inside an element. Syntax: padding: value;",
		"code_lines": [
			".btn {",
			"    background-color: #4a9eff;",
			"    color: white;",
			"    /* Add padding */",
			"}",
		],
		"bug_line": 3,
		"options": [
			{"text": "padding: 12px 24px;", "correct": true},
			{"text": "margin: 12px 24px;", "correct": false},
			{"text": "spacing: 12px 24px;", "correct": false},
		],
		"correct_output": "[  Click Me  ]\n\nButton looks better now!",
		"error_output": "[ClickMe]\n\n⚠ Text crammed against edges",
		"output_type": "browser",
	},
	{
		"id": "css_predict_02",
		"topic": "css",
		"type": "predict_output",
		"title": "Margin vs Padding",
		"timed": false,
		"time_limit": 0,
		"file_name": "style.css",
		"mission_steps": [
			"Read the CSS rule carefully",
			"Think about what margin and padding do",
			"Select the correct description",
		],
		"hint": "Margin = space outside the element. Padding = space inside the element.",
		"code_lines": [
			".box {",
			"    margin: 20px;",
			"    padding: 10px;",
			"    border: 1px solid black;",
			"}",
		],
		"bug_line": -1,
		"options": [
			{"text": "20px outside the border, 10px inside the border", "correct": true},
			{"text": "10px outside the border, 20px inside the border", "correct": false},
			{"text": "30px of total spacing on all sides", "correct": false},
		],
		"correct_output": "20px gap → [border] → 10px gap → content",
		"error_output": "",
		"output_type": "browser",
	},
	{
		"id": "css_free_02",
		"topic": "css",
		"type": "free_type",
		"title": "Set Font Size",
		"timed": false,
		"time_limit": 0,
		"file_name": "style.css",
		"show_output": true,
		"mission_steps": [
			"Set the paragraph font size to 16px",
			"Use the font-size property",
			"Don't forget the units and semicolon!",
		],
		"hint": "The syntax is: font-size: 16px;",
		"code_lines": [
			"p {",
			"    color: black;",
			"    /* Write your property here */",
			"}",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "font-size: ...;",
		"expected_answers": [
			"font-size: 16px;",
			"font-size:16px;",
		],
		"correct_output": "Text is now 16px!\n\nLooks much better.",
		"error_output": "⚠ Font size not applied",
		"output_type": "browser",
	},
	# ── Free Type ──
	{
		"id": "css_free_01",
		"topic": "css",
		"type": "free_type",
		"title": "Make Text Red",
		"timed": false,
		"time_limit": 0,
		"file_name": "style.css",
		"show_output": true,
		"mission_steps": [
			"Write the CSS property to make text red",
			"Use the 'color' property",
			"Don't forget the semicolon!",
		],
		"hint": "The syntax is: color: red;",
		"code_lines": [
			"p {",
			"    /* Write your property here */",
			"}",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "color: ...;",
		"expected_answers": [
			"color: red;",
			"color:red;",
		],
		"correct_output": "[color=RED]This paragraph is now red![/color]",
		"error_output": "⚠ Style not applied",
		"output_type": "browser",
	},
]

# ─── DJANGO CHALLENGES ───────────────────────────────────────────────────────

static var django_challenges: Array = [
	{
		"id": "dj_debug_01",
		"topic": "django",
		"type": "debug",
		"title": "Fix the View",
		"timed": false,
		"time_limit": 0,
		"file_name": "views.py",
		"mission_steps": [
			"This Django view should return a greeting",
			"Find what's wrong with the import",
			"Select the correct fix",
		],
		"hint": "Django responses come from django.http, not django.response.",
		"code_lines": [
			"from django.response import HttpResponse",
			"",
			"def hello(request):",
			"    return HttpResponse('Hello!')",
		],
		"bug_line": 0,
		"options": [
			{"text": "from django.http import HttpResponse", "correct": true},
			{"text": "from django.responses import HttpResponse", "correct": false},
			{"text": "import HttpResponse from django", "correct": false},
		],
		"correct_output": "Hello!",
		"error_output": "ModuleNotFoundError: No module named 'django.response'",
		"output_type": "browser",
	},
	{
		"id": "dj_steps_01",
		"topic": "django",
		"type": "follow_steps",
		"title": "Create a URL Pattern",
		"timed": false,
		"time_limit": 0,
		"file_name": "urls.py",
		"mission_steps": [
			"We have a view called 'hello' in views.py",
			"We need to connect it to the URL '/hello/'",
			"Select the correct URL pattern",
		],
		"hint": "Django URL patterns use path() with a route string and view function.",
		"code_lines": [
			"from django.urls import path",
			"from . import views",
			"",
			"urlpatterns = [",
			"    # Add URL pattern here",
			"]",
		],
		"bug_line": 4,
		"options": [
			{"text": "path('hello/', views.hello, name='hello'),", "correct": true},
			{"text": "url('hello/', views.hello()),", "correct": false},
			{"text": "route('/hello', hello),", "correct": false},
		],
		"correct_output": "Page at /hello/ says:\nHello!",
		"error_output": "Page not found (404)\n/hello/ does not match any URL patterns",
		"output_type": "browser",
	},
	{
		"id": "dj_predict_01",
		"topic": "django",
		"type": "predict_output",
		"title": "What Does This View Return?",
		"timed": false,
		"time_limit": 0,
		"file_name": "views.py",
		"mission_steps": [
			"Read the Django view function",
			"Think about what will appear in the browser",
			"Select the correct output",
		],
		"hint": "String concatenation with + joins the pieces together.",
		"code_lines": [
			"from django.http import HttpResponse",
			"",
			"def welcome(request):",
			"    name = 'Student'",
			"    return HttpResponse('Welcome, ' + name + '!')",
		],
		"bug_line": -1,
		"options": [
			{"text": "Welcome, Student!", "correct": true},
			{"text": "Welcome, name!", "correct": false},
			{"text": "Welcome, + name + !", "correct": false},
		],
		"correct_output": "Welcome, Student!",
		"error_output": "",
		"output_type": "browser",
	},
	{
		"id": "dj_debug_02",
		"topic": "django",
		"type": "debug",
		"title": "Fix the Template Tag",
		"timed": false,
		"time_limit": 0,
		"file_name": "template.html",
		"mission_steps": [
			"This Django template should show the user's name",
			"The template syntax is wrong",
			"Select the correct fix",
		],
		"hint": "Django template variables use double curly braces: {{ variable }}",
		"code_lines": [
			"<h1>Hello, {% name %}!</h1>",
		],
		"bug_line": 0,
		"options": [
			{"text": "<h1>Hello, {{ name }}!</h1>", "correct": true},
			{"text": "<h1>Hello, {# name #}!</h1>", "correct": false},
			{"text": "<h1>Hello, {$ name $}!</h1>", "correct": false},
		],
		"correct_output": "[b]Hello, Mateo![/b]",
		"error_output": "TemplateSyntaxError: Invalid block tag",
		"output_type": "browser",
	},
	{
		"id": "dj_debug_03",
		"topic": "django",
		"type": "debug",
		"title": "Fix the Model Field",
		"timed": false,
		"time_limit": 0,
		"file_name": "models.py",
		"mission_steps": [
			"This model should have a title field",
			"The field type is wrong",
			"Select the correct Django field",
		],
		"hint": "Short text fields in Django use CharField, not StringField.",
		"code_lines": [
			"from django.db import models",
			"",
			"class Post(models.Model):",
			"    title = models.StringField(max_length=200)",
			"    content = models.TextField()",
		],
		"bug_line": 3,
		"options": [
			{"text": "title = models.CharField(max_length=200)", "correct": true},
			{"text": "title = models.VarcharField(max_length=200)", "correct": false},
			{"text": "title = models.TextShortField(max_length=200)", "correct": false},
		],
		"correct_output": "Model created successfully!\n\nPost: title (CharField), content (TextField)",
		"error_output": "AttributeError: module 'django.db.models' has no attribute 'StringField'",
		"output_type": "terminal",
	},
	{
		"id": "dj_steps_02",
		"topic": "django",
		"type": "follow_steps",
		"title": "Return a Template",
		"timed": false,
		"time_limit": 0,
		"file_name": "views.py",
		"mission_steps": [
			"This view should render a template called 'home.html'",
			"We need to use the render() function",
			"Select the correct return statement",
		],
		"hint": "render() takes the request and template name as arguments.",
		"code_lines": [
			"from django.shortcuts import render",
			"",
			"def home(request):",
			"    # Return the template here",
		],
		"bug_line": 3,
		"options": [
			{"text": "return render(request, 'home.html')", "correct": true},
			{"text": "return template('home.html')", "correct": false},
			{"text": "return display(request, 'home.html')", "correct": false},
		],
		"correct_output": "[b]Welcome Home![/b]\n\nPage rendered successfully",
		"error_output": "TemplateDoesNotExist: home.html",
		"output_type": "browser",
	},
	{
		"id": "dj_steps_03",
		"topic": "django",
		"type": "follow_steps",
		"title": "Pass Context to Template",
		"timed": false,
		"time_limit": 0,
		"file_name": "views.py",
		"mission_steps": [
			"We need to pass a 'name' variable to the template",
			"Add a context dictionary to the render call",
			"Select the correct code",
		],
		"hint": "Context is a dictionary passed as the third argument to render().",
		"code_lines": [
			"from django.shortcuts import render",
			"",
			"def greet(request):",
			"    name = 'Mateo'",
			"    # Pass name to the template",
		],
		"bug_line": 4,
		"options": [
			{"text": "return render(request, 'greet.html', {'name': name})", "correct": true},
			{"text": "return render(request, 'greet.html', name)", "correct": false},
			{"text": "return render('greet.html', context=name)", "correct": false},
		],
		"correct_output": "[b]Hello, Mateo![/b]\n\nTemplate rendered with context",
		"error_output": "TypeError: context must be a dict",
		"output_type": "browser",
	},
	{
		"id": "dj_predict_02",
		"topic": "django",
		"type": "predict_output",
		"title": "Template For Loop",
		"timed": false,
		"time_limit": 0,
		"file_name": "list.html",
		"mission_steps": [
			"Read the Django template code",
			"The context has: items = ['Apple', 'Banana']",
			"What will the browser show?",
		],
		"hint": "{% for x in list %} loops through each item.",
		"code_lines": [
			"<ul>",
			"{% for item in items %}",
			"  <li>{{ item }}</li>",
			"{% endfor %}",
			"</ul>",
		],
		"bug_line": -1,
		"options": [
			{"text": "• Apple\n• Banana", "correct": true},
			{"text": "• item\n• item", "correct": false},
			{"text": "• ['Apple', 'Banana']", "correct": false},
		],
		"correct_output": "• Apple\n• Banana",
		"error_output": "",
		"output_type": "browser",
	},
	{
		"id": "dj_free_02",
		"topic": "django",
		"type": "free_type",
		"title": "Write a URL Pattern",
		"timed": false,
		"time_limit": 0,
		"file_name": "urls.py",
		"show_output": false,
		"mission_steps": [
			"Write a URL pattern for the path 'about/'",
			"It should point to views.about",
			"Give it the name 'about'",
		],
		"hint": "path('route/', views.function, name='name')",
		"code_lines": [
			"from django.urls import path",
			"from . import views",
			"",
			"urlpatterns = [",
			"    # Write your URL pattern",
			"]",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "path('about/', ...)",
		"expected_answers": [
			"path('about/', views.about, name='about'),",
			"path('about/', views.about, name='about')",
			"path(\"about/\", views.about, name=\"about\"),",
			"path(\"about/\", views.about, name=\"about\")",
		],
		"correct_output": "/about/ → views.about ✓",
		"error_output": "Invalid URL pattern syntax",
		"output_type": "terminal",
	},
	# ── Free Type ──
	{
		"id": "dj_free_01",
		"topic": "django",
		"type": "free_type",
		"title": "Write the Import",
		"timed": false,
		"time_limit": 0,
		"file_name": "views.py",
		"show_output": false,
		"mission_steps": [
			"Write the import statement for HttpResponse",
			"It comes from the django.http module",
			"Use the 'from ... import ...' syntax",
		],
		"hint": "The syntax is: from django.http import HttpResponse",
		"code_lines": [
			"# Write the import statement below",
			"",
			"def hello(request):",
			"    return HttpResponse('Hello!')",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "from django... import ...",
		"expected_answers": [
			"from django.http import HttpResponse",
		],
		"correct_output": "Hello!",
		"error_output": "ModuleNotFoundError: No module named ...",
		"output_type": "browser",
	},
	# ── Terminal Commands ──
	{
		"id": "dj_term_01",
		"topic": "django",
		"type": "terminal",
		"title": "Create a Virtual Environment",
		"timed": false,
		"time_limit": 0,
		"file_name": "terminal",
		"show_output": true,
		"mission_steps": [
			"Create a Python virtual environment",
			"Name it 'venv'",
			"Use the python -m venv command",
		],
		"hint": "The command is: python -m venv <name>",
		"code_lines": [
			"$ # Create a virtual environment",
			"$ # Type the command below",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "$ python -m venv ...",
		"expected_answers": [
			"python -m venv venv",
			"python3 -m venv venv",
			"py -m venv venv",
		],
		"correct_output": "Creating virtual environment 'venv'...\n\n✓ Virtual environment created successfully!\n\n  venv/\n  ├── bin/\n  ├── lib/\n  └── pyvenv.cfg",
		"error_output": "Error: Invalid command. Check the syntax.",
		"output_type": "terminal",
	},
	{
		"id": "dj_term_02",
		"topic": "django",
		"type": "terminal",
		"title": "Start a Django Project",
		"timed": false,
		"time_limit": 0,
		"file_name": "terminal",
		"show_output": true,
		"mission_steps": [
			"Create a new Django project",
			"Name it 'myproject'",
			"Use django-admin startproject",
		],
		"hint": "The command is: django-admin startproject <name>",
		"code_lines": [
			"(venv) $ # Virtual env is active",
			"(venv) $ pip install django  # Already done",
			"(venv) $ # Now create the project",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "$ django-admin startproject ...",
		"expected_answers": [
			"django-admin startproject myproject",
		],
		"correct_output": "✓ Project 'myproject' created!\n\n  myproject/\n  ├── manage.py\n  └── myproject/\n      ├── __init__.py\n      ├── settings.py\n      ├── urls.py\n      └── wsgi.py",
		"error_output": "Error: Command not recognized.",
		"output_type": "terminal",
	},
	{
		"id": "dj_term_03",
		"topic": "django",
		"type": "terminal",
		"title": "Run Migrations",
		"timed": false,
		"time_limit": 0,
		"file_name": "terminal",
		"show_output": true,
		"mission_steps": [
			"Apply the database migrations",
			"Use python manage.py",
			"The command to apply migrations is 'migrate'",
		],
		"hint": "The command is: python manage.py migrate",
		"code_lines": [
			"(venv) $ cd myproject",
			"(venv) $ # Apply database migrations",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "$ python manage.py ...",
		"expected_answers": [
			"python manage.py migrate",
			"python3 manage.py migrate",
			"py manage.py migrate",
		],
		"correct_output": "Operations to perform:\n  Apply all migrations: admin, auth, contenttypes, sessions\nRunning migrations...\n  Applying contenttypes.0001_initial... OK\n  Applying auth.0001_initial... OK\n  Applying sessions.0001_initial... OK\n\n✓ All migrations applied!",
		"error_output": "Error: Unknown command.",
		"output_type": "terminal",
	},
	{
		"id": "dj_term_04",
		"topic": "django",
		"type": "terminal",
		"title": "Create a Superuser",
		"timed": false,
		"time_limit": 0,
		"file_name": "terminal",
		"show_output": true,
		"mission_steps": [
			"Create an admin superuser account",
			"Use python manage.py",
			"The command is 'createsuperuser'",
		],
		"hint": "The command is: python manage.py createsuperuser",
		"code_lines": [
			"(venv) $ # Create an admin account",
			"(venv) $ # So you can access /admin",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "$ python manage.py ...",
		"expected_answers": [
			"python manage.py createsuperuser",
			"python3 manage.py createsuperuser",
			"py manage.py createsuperuser",
		],
		"correct_output": "Username: admin\nEmail: admin@djangoquest.com\nPassword: ********\nPassword (again): ********\n\n✓ Superuser created successfully!",
		"error_output": "Error: Unknown command.",
		"output_type": "terminal",
	},
	{
		"id": "dj_term_05",
		"topic": "django",
		"type": "terminal",
		"title": "Run the Development Server",
		"timed": false,
		"time_limit": 0,
		"file_name": "terminal",
		"show_output": true,
		"mission_steps": [
			"Start the Django development server",
			"Use python manage.py",
			"The command is 'runserver'",
		],
		"hint": "The command is: python manage.py runserver",
		"code_lines": [
			"(venv) $ # Start the dev server",
			"(venv) $ # So we can see our site!",
		],
		"bug_line": -1,
		"starter_code": "",
		"placeholder": "$ python manage.py ...",
		"expected_answers": [
			"python manage.py runserver",
			"python3 manage.py runserver",
			"py manage.py runserver",
		],
		"correct_output": "Watching for file changes with StatReloader\nPerforming system checks...\n\nSystem check identified no issues.\n\nStarting development server at http://127.0.0.1:8000/\nQuit the server with CONTROL-C.\n\n🚀 Server is running!",
		"error_output": "Error: Unknown command.",
		"output_type": "terminal",
	},
]

# ─── UTILITY: Get all challenges ─────────────────────────────────────────────

static func get_all_challenges() -> Array:
	return python_challenges + html_challenges + css_challenges + django_challenges

static func get_challenges_by_topic(topic: String) -> Array:
	match topic:
		"python": return python_challenges
		"html": return html_challenges
		"css": return css_challenges
		"django": return django_challenges
		_: return []
